{{- if .Values.brokerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-broker-token
type: Opaque
data:
  "{{ .Values.scmType}}-broker-token-key": {{ .Values.brokerToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.scmToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.scmToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.bitbucketPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: bitbucketpassword
type: Opaque
data:
  "bitbucketPassword": {{ .Values.bitbucketPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.jiraPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: jirapassword
type: Opaque
data:
  "jiraPassword": {{ .Values.jiraPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.crPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: crpassword
type: Opaque
data:
  "crPassword": {{ .Values.crPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.snykToken }}
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token
type: Opaque
data:
  "snyk-token-key": {{ .Values.snykToken | b64enc | quote }}
{{- end }}